<template>
	<div class="flex justify-start items-center">
		<h1 class="text-sm font-medium opacity-70 flex items-center px-[6px]">
			Tags
		</h1>
	</div>
	<div class="flex space-x-2 space-y-2 mt-3 w-full flex-wrap">
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Turorials</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Coding</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Tools</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>English</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Gaming</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Travel</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>Arts</UButton
			>
		</div>
		<div>
			<UButton
				color="neutral"
				variant="soft"
				size="sm"
				class="cursor-pointer"
				>History</UButton
			>
		</div>
	</div>
</template>
